version: "3.9"
services:
  backend:
    build:
      context: ..
      dockerfile: backend/Dockerfile
    container_name: homecam-backend
    environment:
      - MEDIA_ROOT=/media
      - DB_PATH=/data/homecam.db
    volumes:
      - ../media:/media
      - ../data:/data
    restart: unless-stopped

  nginx:
    image: nginx:1.27
    container_name: homecam-nginx
    depends_on:
      - backend
    volumes:
      - ../frontend/dist:/usr/share/nginx/html:ro
      - ../media:/media:ro
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - "8080:8080"
    restart: unless-stopped
