version: "3.9"
services:
  homecam:
    build:
      context: ..
    container_name: homecam
    environment:
      - MEDIA_ROOT=/media
      - RECORDINGS_ROOT=/recordings
      - DB_PATH=/data/homecam.db
      # SERVICE can be 'all', 'backend', or 'frontend'
      - SERVICE=all
    volumes:
      - /mnt/homecam/media:/media
      - /mnt/homecam/data:/data
      - /mnt/homecam:/recordings
    ports:
      - "8090:8090"
      - "8091:8091"
    restart: unless-stopped
