version: "3.9"
services:
  backend:
    build:
      context: ..
      dockerfile: backend/Dockerfile
    container_name: homecam-backend
    environment:
      - MEDIA_ROOT=/media
      - DB_PATH=/data/homecam.db
      - RECORDINGS_ROOT=/recordings
    volumes:
      - /mnt/homecam/media:/media
      - /mnt/homecam/data:/data
      - /mnt/homecam:/recordings
    restart: unless-stopped

  nginx:
    image: nginx:1.27
    container_name: homecam-nginx
    depends_on:
      - backend
    volumes:
      - ../frontend/dist:/usr/share/nginx/html:ro
      - /mnt/homecam/media:/media:ro
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - "8090:8090"
    restart: unless-stopped
