version: "3.9"
services:
  homecam:
    build:
      context: ..
    container_name: homecam
    volumes:
      - /mnt/homecam/media:/media
      - /mnt/homecam/data:/data
      - /mnt/homecam:/recordings
    ports:
      - "8090:8090"
      - "8091:8091"
    restart: unless-stopped
